### ISSUE TITLE
Smoke test entire site

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#10]
Confirm all site functionality, including Twitter submission, click throughs, video plays, Event form submission, downloads, etc. @chrsmrtn0

**Comment by RobErskine** [comment]
Could be a good opportunity to implement Cypress if we have time?

**Comment by chrsmrtn0** [comment]
Functionally, the site works fine. Where it starts to fall flat is within Performance and Accessibility. Running a Google Lighthouse report scores the site lower than 40/100 in both disciplines, leaving much room for improvement.
[Lighthouse Report.pdf](https://github.com/CityOfBoston/onebostonday/files/1789886/Lighthouse.Report.pdf)

**Comment by RobErskine** [comment]
Functionally, the site works fine. Any tickets for accessibility, performance, etc should be submitted as a new issue.
