### ISSUE TITLE
Reset Acts of Kindness counter

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#11]
Until we have the 2018 Wayin feed connected and collecting new posts, please reset the counter to display the final 2017 number which was over 43,000. @RobErskine

**Comment by RobErskine** [comment]
@chrsmrtn0 @jkvill1  Up on staging as part of  commit: [1a419a6751](https://github.com/CityOfBoston/onebostonday/commit/1a419a67514d5b20974903f77c303af7de4f8080)

**Comment by chrsmrtn0** [comment]
Confirmed, the counter is currently at 43,532. This ticket can be closed.
