### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#12]
Please remove all social posts that now have broken images in them. @RobErskine

**Comment by RobErskine** [comment]
This can be done within Wayin.

**Comment by RobErskine** [comment]
Found a way to do this in code. Images will still technically 404 and throw errors in the console, but I'm removing them visually from the DOM when the feed loads.

**Comment by RobErskine** [comment]
@chrsmrtn0 @jkvill1  Up on staging as part of  commit: [1a419a6751](https://github.com/CityOfBoston/onebostonday/commit/1a419a67514d5b20974903f77c303af7de4f8080)

**Comment by chrsmrtn0** [comment]
@jkvill1 Confirmed, 404 images have been hidden on all browsers, mobile and desktop.
