### ISSUE TITLE
Add Aria roles and regions

### ISSUE THREAD

**Issue by chrsmrtn0** [CityOfBoston/onebostonday#14]
Globally, the site requires aria roles and regions for easy Accessibility navigation. Areas such as header, nav, main, and footer should get us through and ADA compliance, but we should consider splitting up some of the pages, such as the community/planning sections, with custom labels.

**Comment by RobErskine** [comment]
@chrsmrtn0 Up on staging as part of  commit: [1a419a6751](https://github.com/CityOfBoston/onebostonday/commit/1a419a67514d5b20974903f77c303af7de4f8080)

**Comment by chrsmrtn0** [comment]
These are all set now.
