### ISSUE TITLE
Update Twitter count for new character count

### ISSUE THREAD

**Issue by RobErskine** [CityOfBoston/onebostonday#16]
Twitter recently updated their tweet count from 140 characters to 280 characters. We should update the character count accordingly.

**Comment by RobErskine** [comment]
Up on staging as part of  commit: [1a419a6751](https://github.com/CityOfBoston/onebostonday/commit/1a419a67514d5b20974903f77c303af7de4f8080)

**Comment by chrsmrtn0** [comment]
@RobErskine Confirmed, the new 280 character count is in place and working correctly
