### ISSUE TITLE
Add in Media Kit to the Press Page

### ISSUE THREAD

**Issue by RobErskine** [CityOfBoston/onebostonday#17]
As part of Phase 1 launch we want to include a new Media Kit to the Press Page to let people know what One Boston Day is all about.

**Comment by RobErskine** [comment]
Pushed to http://staging.onebostonday.org/press/ as part of commit: [7891ffb](https://github.com/CityOfBoston/onebostonday/commit/7891ffb01443db9ee75699f2c5290c13aab3de17)

@chrsmrtn0 ready to review.

**Comment by chrsmrtn0** [comment]
@RobErskine confirmed this is up and working as expected across browsers. You can close this.
