### ISSUE TITLE
AWS / SSL updates

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#18]
Let's connect in person about setting up the S3 bucket and getting the cert.

**Comment by edesilets** [comment]
@jkvill1 I have completed the following tasks

- [x] Created S3 bucket
- [x] Setup Cloudfront
- [x] Purchased a SAN Cert and add it to ACM (AWS Certificate Manager)
- [x] Purchased the domain of 1boston.org
- [x] Moved domains from Rackspace to Route53 (AWS service)
- [x] Point domains at the new AWS production site (Just waiting for the go ahead)

**Note:** The SAN Cert covers the following sub-domains:
- www.1boston.org
- www.1bostonday.com
- www.1bostonday.org
- www.onebostonday.org
- www.onebostonday.us

**This SSL cert is only good for 1 year from today (4/4/2018).**

**Comment by RobErskine** [comment]
Not critical for today but where did we land with getting SSL setup for onebostonday.org? Hitting https now just spins. cc @edesilets

**Comment by edesilets** [comment]
@RobErskine SSL for One Boston Day's Cloudfront instance is ready to go. Currently your are seeing HTTPS not load because it's pointed at an S3 bucket which can't have HTTPS. Once the DNS is pointed at the Cloudfront instance it will redirect from HTTP to HTTPS and everything will be right as rain. Note: I have the redirects working for Cloudfront.

**Comment by RobErskine** [comment]
What steps do we need to take to point the DNS from s3 to cloudfront? Are we waiting for traffic to die down?

**Comment by edesilets** [comment]
The craft end point needed to be fixed, but it looks like you fixed it last night. [See Commit](https://github.com/CityOfBoston/onebostonday/commit/afcdf9a9c55552b65f91af3ad303458a1ccd4dd4) I should be able to export [commit](https://github.com/CityOfBoston/onebostonday/commit/9f7a44a54e93d6967abddd4c8d5f508e47c37177) to production now.  Once this change is live then I should be good to repoint the DNS to Cloudfront.
