### ISSUE TITLE
Update Wayin API

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#20]

**Comment by RobErskine** [comment]
@mcclaskiem I started to work on this on the [feature/wayin-api-update](https://github.com/CityOfBoston/onebostonday/tree/feature/wayin-api-update) branch.

You'll need to compare the json keys and values from `/feed/feed.json` against the [new WayIn API endpoint](https://xapi.wayin.com/xapi/content/3/filter?key=103adfe9-a7b9-4824-9916-052f7339d73a&format=json&max=1000&collectionId=co-2ny8jdhvr07p7ogdqyf).

You'll then need to update the data that you pass into each function that populates that twitter / instagram tiles around [line 194](https://github.com/CityOfBoston/onebostonday/commit/ee78be6b72f915b8b272c3ba07cf0194e5b1705d#diff-b37498ffbef3abec39bdf3f887537ddfR194) of `build/js/main.js`.

If you see any ways to improve this (of which there are _many_), feel free to do so if we have the time allotted.

**Comment by RobErskine** [comment]
Max updated the Wayin API stuff. I merged it into our Craft branch so that we could test on staging: http://staging.onebostonday.org/

cc: @jkvill1

**Comment by ChristopherAlberto-SRX** [comment]
Platform: wayin
Environment: Staging
URL: https://xapi.wayin.com/xapi/content/3/filter?key=103adfe9-a7b9-4824-9916-052f7339d73a&format=json&max=1000&collectionId=co-2ny8jdhvr07p7ogdqyf

Endpoint fails to update when a user attempt to reject a post that was previously approved.

STR:

1. W/ valid creds sign into the Wayin App portal (ping directly for URL)
2. Open the 1BOSday collection (ping directly for URL)
3. Open the Endpoint and observe "totalrecords" value
4. Approve a post (confirm with production on which to publish)
5. Refresh Endpoint and observe "totalrecords" value
6. Via the Wayin App portal select Published from the moderation status drop down
7. Reject the post you just published
8. Refresh Endpoint and observe "totalrecords" value
9. Observe that the value remains the same

Expected Result:
Rejecting a post that has been previously published removes the post from the endpoint.
Rejected posts that has been previously published do not appear on the front end.

**Comment by jkvill1** [comment]
@mcclaskiem Just a reminder we need to also update the jumbotron feed to hit the new API. See @RobErskine for details.

**Comment by RobErskine** [comment]
@jkvill1 Jumbotron is all updated. We good to close?

**Comment by ChristopherAlberto-SRX** [comment]
Platforms: n/a
Environment: Production
URL: http://onebostonday.org/tweets

Video posts are rendering copy only. 
Video fails to load and leave an empty white space next to the copy.

**Comment by ChristopherAlberto-SRX** [comment]
Platforms: n/a
Environment: Production
URL: http://onebostonday.org/

--Appending here as this fix should resolve the following issue.
Video posts are not rendering on the home page.
Only the copy of the post draws on screen while a loading icon appears for the video thumbnail.

**Comment by RobErskine** [comment]
Should be good now. Check the boloco post for reference

**Comment by ChristopherAlberto-SRX** [comment]
Fix verified on staging.
