### ISSUE TITLE
The "aria-role" attribute is not valid for the "nav" element.

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#21]
Environment: Staging
URL: http://staging.onebostonday.org/

Found: Main navigation has "aria-role" attribute  assigned to it. 
`<nav class="main-nav" aria-role="navigation" aria-label="Main Navigation">`

> In the majority of cases setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and not recommended as these properties are already set by the browser.
https://www.w3.org/TR/html5/infrastructure.html#default-implicit-aria-semantics

**Comment by mcclaskiem** [comment]
Are we removing both aria-labels here? @calbertohhcc

**Comment by ChristopherAlberto-SRX** [comment]
Waived
