### ISSUE TITLE
Tweet input form has no corresponding label

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#22]
Found: Tweet field is missing a text label.
> If a text label for a form control is visible, use the <label> element to associate it with its respective form control. If there is no visible label, either provide an associated label, add a descriptive title attribute to the form control, or reference the label(s) using aria-labelledby.

**Comment by mcclaskiem** [comment]
This is now on staging

**Comment by ChristopherAlberto-SRX** [comment]
A form label is present but does not contain any content. 
This label element contains no text. It should contain an appropriate text label.
`<label for="tweet-field" aria-hidden="false" class="aria-hidden"></label>`

**Comment by mcclaskiem** [comment]
This is now on staging @calbertohhcc

**Comment by ChristopherAlberto-SRX** [comment]
Fix verified on staging.
