### ISSUE TITLE
Install export plugin

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#24]
Ensure all URLs are relative.

**Comment by RobErskine** [comment]
Git repo for the export tool can be found on HHCC's Stash here: https://stash.hhcc.com/projects/HHCC/repos/craft-export-tool/browse

**Comment by mcclaskiem** [comment]
This is on staging now and installed

**Comment by edesilets** [comment]
Settings for the export plugin are set.
