### ISSUE TITLE
Create API endpoint to scrape

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#25]

**Comment by RobErskine** [comment]
You can reference this endpoint that we used for another project: https://stash.hhcc.com/projects/JH/repos/different-world/browse/craft/templates/api/v1/assets/get.twig

**Comment by mcclaskiem** [comment]
http://staging.onebostonday.org/api/v1/assets/get.json

This feed is now available at the above link.

Notes:

The feed does not include the following folders which we will just move once manually into the AWS bucket from our public directory. cc: @RobErskine @edesilets 

- `img`
- `fonts`
- `pdf`
- `video`
- `zip`

**Comment by edesilets** [comment]
@RobErskine that twig example out of date. I think a more relevant example would be from Brigham. I wrote up some docs a couple of minutes ago on the accepted JSON format in confluence. @mcclaskiem is aware of the changes that need to be made. If any issues occur we will hash them out.
