### ISSUE TITLE
Pull video Watch Now button on homepage

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#29]

**Comment by jkvill1** [comment]
Remove Twitter player card, use static image instead of video play.

**Comment by mcclaskiem** [comment]
This on staging now

**Comment by chrsmrtn0** [comment]
Confirmed, play now has been removed from desktop cross browser and mobile.

**Comment by jkvill1** [comment]
@chrsmrtn0 Can you also confirm the Twitter metadata before I close this?

**Comment by RobErskine** [comment]
Can confirm the image was pulled from current prod ![twitter card](https://d3vv6lp55qjaqc.cloudfront.net/items/3s2C2c1G3n3T2n2n1U1R/Screen%20Shot%202018-04-05%20at%205.37.00%20PM.jpg?X-CloudApp-Visitor-Id=135073). Just need to make sure it's there after we push the new craft stuff
