### ISSUE TITLE
Tweets not pulling in associated photos

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#32]
On production.

**Comment by RobErskine** [comment]
Fixed on production for now. @mcclaskiem check out what I did [on the master branch](https://github.com/CityOfBoston/onebostonday/blob/master/build/js/main.js#L363) to make sure you can merge properly. Your initial fix was close, just needed to update the conditional.

**Comment by mcclaskiem** [comment]
This is on staging now

**Comment by ChristopherAlberto-SRX** [comment]
Environment: Staging & Production
Post URL: https://twitter.com/MrDurney/status/981967267662630912/photo/1

Images are pulling in however if a tweet has multiple images associated with the post we are only grabbing the first to add to our thumbnail.

Is this intended behavior?

**Comment by mcclaskiem** [comment]
@jkvill1 Is only pulling one image ok for now? Building multi-image support will require us re-doing the feed templating

**Comment by jkvill1** [comment]
Ok, one image is fine then, thanks.

**Comment by ChristopherAlberto-SRX** [comment]
Marking ticket as closed based on comments above.

> Single image support when dealing with multiple images in a tweet
