### ISSUE TITLE
Press - Date is adding a exta space

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#33]
Environment: Staging & Production
URL: http://www.onebostonday.org/press/

STR:

1. Go to the URL listed above on desktop
2. Observe line "‘One Boston Day’ Video Urges..."
3. Observe date below it has an additional space in front of it.

![capture](https://user-images.githubusercontent.com/35541168/38430875-8b6da7e2-3990-11e8-88fc-39b24438a660.PNG)

Issue is present on mobile as well.
If a new line starts with the date then a space is added before the copy.
If it wraps and the source appears on the 2nd line the space is not added.

Can we make date inline with the link?

**Comment by RobErskine** [comment]
Could fix this by adding padding-right to the title, and removing padding-left from the date. This is pretty low priority though so focus on the more critical stuff first

**Comment by mcclaskiem** [comment]
I have this fix locally already just never pushed it yesterday with everything that was going on. Will get this worked in with next big update on Monday

**Comment by mcclaskiem** [comment]
This is now on staging @calbertohhcc

**Comment by ChristopherAlberto-SRX** [comment]
Fix verified on staging.
