### ISSUE TITLE
Stories section

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#36]
1.) Need to display Firstname Lastname On behalf of on individual pages. 

2.) Need photo display solution.

3.) Let's just make the thumbnails flush left under the main photo window vs. spaced the way they are now. 

4.) If no photos are present, remove section. Currently an empty blue outline remains where the photos would be.

5.) If no links are present, remove section. Currently the Links header remains regardless.

**Comment by ChristopherAlberto-SRX** [comment]
6) Make image transform. Site loading giant images upfront for thumbnails.

**Comment by mcclaskiem** [comment]
All of this should be accounted for now on staging

**Comment by ChristopherAlberto-SRX** [comment]
All edits with the exception of request # 3 were made.

> 3.) Let's just make the thumbnails flush left under the main photo window vs. spaced the way they are now.

@jfalvey  if i'm reading this right you want the thumbnails under the main image to be left aligned with the main image right? Currently they are centered like this --
![capture](https://user-images.githubusercontent.com/35541168/38742227-f8a94ac2-3f09-11e8-9872-415b15845ee5.PNG)
If what is in that image is accurate then please ignore this comment @RobErskine and close this ticket.

**Comment by jkvill1** [comment]
@calbertohhcc Max and I worked through this offline and the staging site is now correct. They should be centered. And not present if there's only one photo.
