### ISSUE TITLE
Mobile - Story Pages - Add padding to body container

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#38]
Platforms: Global Mobile
Environment: Staging
URL: n/a

Story pages require some left and right padding in the body section.
Currently the copy is resting against the edge of the device.

**Comment by mcclaskiem** [comment]
This is on staging now

**Comment by ChristopherAlberto-SRX** [comment]
This issue remains present on the Story main page.
Can you please update the Story page to reflect the same amount of padding as in the individual story pages.

**Comment by ChristopherAlberto-SRX** [comment]
Kicking over the Rob as he is now handling the frontend fixes.

**Comment by RobErskine** [comment]
fixed on staging.onebostonday.org

**Comment by ChristopherAlberto-SRX** [comment]
Fix verified on staging.
