### ISSUE TITLE
Homepage video updates

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#40]
PSDs here: https://drive.google.com/open?id=1Cq_4HBawhk_WDB2rM_iZJ2k9SZJJN52O

Copy will change from what's in the comps.

**Comment by RobErskine** [comment]
Up on http://staging.onebostonday.org. It's using the same video modal that was up there before, just dynamic now. You can edit the videos in the CMS by going to Entries > Singles > Home.

**Comment by ChristopherAlberto-SRX** [comment]
![capture](https://user-images.githubusercontent.com/35541168/38640162-7e05e672-3da1-11e8-84c5-23f2b9e51f8f.PNG)

Thumbnails are not rendering the same size when viewed in IE 11.
Also, if possible, can we please reduce the size of the play icon to better match the proof?

**Comment by RobErskine** [comment]
Just pushed up a fix that should fixed this @calbertohhcc

**Comment by ChristopherAlberto-SRX** [comment]
Fix verified on staging.
