### ISSUE TITLE
Stories - custom URLs inherenting parent URL

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#46]
Platform: Global
Environment: S3 & RS
Story URL: http://staging.onebostonday.org/stories/brittany-loring
Link URL: http://staging.onebostonday.org/stories/Brittanyfund.org

Links within stories are adding the parent page URL to the beginning of all custom links.
Example:

In the Brittany Loring page there's a custom link in the CMS for Brittanyfund.org.
However when you view this link on the site it's coming up as http://staging.onebostonday.org/stories/Brittanyfund.org.

**Comment by RobErskine** [comment]
@jkvill1  This is a content issue and should be fixed by prepending a protocol in the CMS (http:// or https://)

**Comment by ChristopherAlberto-SRX** [comment]
@jkvill1 Rob is spot on.
I was able to resolve this one link by just adding the correct protocol.

Please note that I only resolved the issue for the one link listed in this ticket.
Someone will need to go in and update all other custom URLs to include the correct protocol.

**Comment by ChristopherAlberto-SRX** [comment]
I went ahead and updated the links that needed updating.
Not all additional links were missing https://

**Comment by jkvill1** [comment]
Noted, guys, thanks. I'll make sure to do that going forward with the other entries.
