### ISSUE TITLE
Add retweets to ticker

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#47]

**Comment by ChristopherAlberto-SRX** [comment]
@RobErskine please let @jkvill1 know when this change is made so we can review the number.

**Comment by RobErskine** [comment]
Turned "exclude retweets" to off. ![Wayin Retweets](https://cl.ly/1v1N1y3n281v/Screen%20Shot%202018-04-13%20at%202.17.34%20PM.jpg). Not sure how long it will take for Wayin to update, or if it will only work for retweets moving forward.
