### ISSUE TITLE
Stories - Share links 

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#48]
Share links are currently pointing to staging and not the environment they are being hosted on.

Example:
http://staging-aws.onebostonday.org/stories/amanda-north/

Social share link is driving to http://staging.onebostonday.org/stories/amanda-north

**Comment by RobErskine** [comment]
Since we're using the scraping tool the tool will pull whatever the current url is. To remedy this, we're hardcoding the production links. As soon as these pages are live we should be good. Can be see on on staging.onebostonday.org

**Comment by ChristopherAlberto-SRX** [comment]
verified on staging.
Links are now pointing to the intended prod URL
