### ISSUE TITLE
Wayin wall rendering out of order

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#49]
This is present on Production.

Posts are not coming in order; appear random.
Should be coming in reverse chronological order.

**Comment by RobErskine** [comment]
Can you dig in and see what order they are actually coming in at? Are they coming in order in the API? Is it just that instagram / twitter are not in order? etc?

**Comment by ChristopherAlberto-SRX** [comment]
Sorry for not including all this information in the original ticket.
Endpoint URL: https://xapi.wayin.com/xapi/content/3/filter?key=103adfe9-a7b9-4824-9916-052f7339d73a&format=json&max=1000&collectionId=co-2ny8jdhvr07p7ogdqyf
Site URL: http://onebostonday.org/
Wayin collection: (ping me)

The wayin published bucket matches what the order of what is present on the site as well as the endpoint. This appears to be an issue on their end.

Kicking over to @jkvill1 as she is going to have Dunn reach out to wayin.

**Comment by ChristopherAlberto-SRX** [comment]
This appears to be working again.
Newly published posts go to the top of the stack.
