### ISSUE TITLE
Hook up social feed to jumbotron, update front end to spec

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#5]
2017 #onebostonday feed only, via Wayin.

The display is in a 16:10 aspect ratio.
The total pixel count is 768 by 480.

Due: EOD Wednesday, testing on Thursday at 1pm.

**Comment by RobErskine** [comment]
The display dimensions were incorrect. We correctly matched the display to 1920x1080 16:9 and can be seen live here http://onebostonday.org/tweets. Completed in commit (https://github.com/CityOfBoston/onebostonday/commit/122c366968318f5b63b1ccb7beb6ca4d7e40e579)
