### ISSUE TITLE
AWS - Video background missing

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#50]
Platforms: Global
Environment: AWS S3
URL: http://staging-aws.onebostonday.org/

Video background is not present.
This issue is only present on aws staging.
Video plays without issue on production and the rackspace staging site.

**Comment by RobErskine** [comment]
We're removing the video with the new video layout. Should just be a static asset. The permissions were messed up in AWS so this should be resolved.
