### ISSUE TITLE
Firefox - Close Video copy appears when expanding video

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#51]
Platforms: Firefox v59
Environment: S3 & RS
URL: http://staging.onebostonday.org/

STR:

1. Go to http://staging.onebostonday.org/
2. Play any one of the 3 videos
3. Observe text "close video" appears
![capture](https://user-images.githubusercontent.com/35541168/38749452-a9f57a98-3f1f-11e8-8176-20211649c6e3.PNG)
 in the top left

**Comment by RobErskine** [comment]
fixed on staging.onebostonday.org

**Comment by ChristopherAlberto-SRX** [comment]
Fixed verified on staging.
