### ISSUE TITLE
Your connection is not secure: Insecure Content Blocked

### ISSUE THREAD

**Issue by ChristopherAlberto-SRX** [CityOfBoston/onebostonday#54]
Platforms: Global
Environment: Production
URL: https://onebostonday.org/

Site is being labeled as "not secure". On certain browsers, Win10 Firefox & IE, users are now required to add the site as an exception just to gain access. Others, like Chrome, are only flagging this in the address bar.

Note:
The network tab lists the following css file as being blocked. This may be causing the issue.
mixed content: http://www.onebostonday.org/fonts/448630/7132208D376542C8A.css

**Comment by RobErskine** [comment]
Typography.com (our web font provider) was setup to look at http://onebostonday.org. I just set it up so that it now calls from https. This should fix the blocking issue.

That being said, we're getting other mixed media warnings (not errors) for images we're loading as well. Craft was set up to put assets on the Amazon s3 CDN as http://. I've updated this on staging to reference https://. These mixed media warnings should go away next time we deploy.

**Comment by ChristopherAlberto-SRX** [comment]
Test conducted using the live address given by a google search of "one boston day"
URL: https://onebostonday.org/

Bases on tests run on multiple validation sites i'm getting certificate mismatch error.
https://www.ssllabs.com/ssltest/analyze.html?d=onebostonday.org
https://www.sslshopper.com/ssl-checker.html#hostname=https://onebostonday.org/

At the browser level the "Your connection is not secure" error only appears to be happening in Firefox and Safari. Chrome and Edge are resolving the initial issue which is why we aren't seeing it in those browsers.
A more detailed explanation can be found here:
https://support.mozilla.org/en-US/questions/1132690
https://www.thesslstore.com/knowledgebase/ssl-support/troubleshooting-name-mismatch-web-browser/

If what is listed above is true in our situation then this could be a possible solution:
https://stackoverflow.com/questions/19104215/node-js-express-js-chain-certificate-not-working

**Comment by RobErskine** [comment]
Hey @calbertohhcc this should be all resolved? Can you confirm and close?

**Comment by ChristopherAlberto-SRX** [comment]
Verified as fixed using the same tools listed in my initial comment.
