### ISSUE TITLE
Reset website Acts of Kindness counter for 2017

### ISSUE THREAD

**Issue by jkvill1** [CityOfBoston/onebostonday#6]
Due for review on staging: Tues afternoon

**Comment by RobErskine** [comment]
Updated to wayin endpoint. Can be found via the api here: http://one-boston-day-wayin-api.hhcctech.com/wayin/count.json. Also updated on the homepage in commit (https://github.com/CityOfBoston/onebostonday/commit/e7e8609e9502635a9489f5a26dab24d631b2ba06)
